### ISSUE TITLE
Error with extension f90

### ISSUE THREAD

**Issue by physkets** [caglartoklu/fortran_line_length.vim#1]
Hey! I get the following error when I open a '.f90' file:

```
Error detected while processing function <SNR>36_SetLineLenghtAccordingToFileExtension..<SNR>36_SetLineLengthForFortranExtended:
line    4:
E492: Not an editor command:     Decho "extended"
```

Is this a plugin issue? I don't understand.

**Comment by caglartoklu** [comment]
Hi physkets,
Thanks for the report.
Yes, this is about the plugin itself.
I will commit a fix for this problem.

**Comment by caglartoklu** [comment]
I have updated the code in [395b7d3](https://github.com/caglartoklu/fortran_line_length.vim/commit/395b7d3971b3add31b8793d73feddcd835ea27a5).
It should fix the problem, can you please check it?

**Comment by physkets** [comment]
Ran a `:PluginUpdate`. Opening a fortran90 file gives the same error.

Could it be due to another plugin? When I tried typing beyond a line length of 132, Vim automatically takes me to the next line. It does not let me type ahead. Is this normal behaviour?

The other plugins I have are:

Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-sensible'
Plugin 'altercation/vim-colors-solarized'
Plugin 'w0ng/vim-hybrid'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'scrooloose/syntastic'
Plugin 'valloric/listtoggle'

**Comment by caglartoklu** [comment]
Could it be that you have not restarted Vim after running a `:PluginUpdate` ?
Because, if you have the latest version of `fortran_line_length`, the line with `Decho` does not exist anymore and there is nothing that could trigger that error.
